[theme]
# Main colors
primaryColor = "#00ff88"        # Bright green for buttons and interactive elements
backgroundColor = "#0e1117"     # Dark background
secondaryBackgroundColor = "#262730"  # Slightly lighter for cards/sections
textColor = "#ffffff"          # White text

# Extra customization
font = "sans serif"

[server]
enableStaticServing = true