[theme]
# Main colors
primaryColor = "#FF6B4A"        # Vibrant orange for buttons and interactive elements
backgroundColor = "#1E2A3A"     # Navy blue background
secondaryBackgroundColor = "#2D3B4E"  # Lighter navy for cards/sections
textColor = "#E6E6E6"          # Light gray text

# Extra customization
font = "monospace"

[server]
enableStaticServing = true