[theme]
# Main colors
primaryColor = "#4A90E2"  # Soft blue for interactive elements
backgroundColor = "#0D1B2A"  # Deep navy background for a sleek look
secondaryBackgroundColor = "#1B263B"  # Dark slate blue for sections
textColor = "#F0F4F8"  # Very light gray for readability
accentColor = "#FFB400"  # Warm amber for accents or highlights
borderColor = "#223B5F"  # Muted blue-gray for subtle borders

# Extra customization
font = "monospace"

[server]
enableStaticServing = true